### PR TITLE
WIP: Rip out code to make Debian-compatible

### PR DESCRIPTION
**Pull request by scottcunningham**

### CODE REVIEW

**Comment by scottcunningham** [comment]
Needs to install pkg_resources, that shouldn't have been removed. Should also investigate other dependencies I removed. I thought our deb would take care of it, but apparently not.

**Comment by scottcunningham** [comment]
Fixed.

**Comment by k3ypad** [comment]
👍  - 👠 d

**Comment by mlrobinson** [comment]
LGTM

**Pull request merged**
